import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from src.db.session import SessionLocal
from src.core.analytics import (
    get_media_impact_stats,
    get_media_type_comparison,
    get_revenue_with_posts_timeline,
    get_posts_with_impact,
)
from src.ui.state import business_id


def show_media_impact() -> None:
    db = SessionLocal()
    try:
        st.title("Media Impact Analysis")
        st.markdown("See how your social media posts (reels and stories) affect your sales")

        stats = get_media_impact_stats(db, business_id())
        if stats["total_posts"] == 0:
            st.info("No media posts found. Add posts in Data Management to see their impact on sales.")
            return

        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric("Total Posts", stats["total_posts"])
        with col2:
            st.metric("Reels", stats["total_reels"])
        with col3:
            st.metric("Stories", stats["total_stories"])
        with col4:
            st.metric("Avg Engagement", f"{stats['avg_engagement']:.0f}")

        col5, col6 = st.columns(2)
        with col5:
            st.metric("Avg Sales Lift", f"{stats['avg_lift']:.1f}%", help="Average % increase in daily sales after posting")
        with col6:
            st.metric(
                "Est. Incremental Revenue",
                f"₹{stats['total_incremental_revenue']:,.2f}",
                help="Estimated additional revenue generated by posts",
            )

        st.divider()

        comparison = get_media_type_comparison(db, business_id())
        col1, col2 = st.columns(2)

        with col1:
            st.subheader("Reels vs Stories Performance")
            comparison_data = [
                {"Type": "Reels", "Count": comparison["reels"]["count"], "Avg Lift %": comparison["reels"]["avg_lift"],
                 "Avg Engagement": comparison["reels"]["avg_engagement"]},
                {"Type": "Stories", "Count": comparison["stories"]["count"], "Avg Lift %": comparison["stories"]["avg_lift"],
                 "Avg Engagement": comparison["stories"]["avg_engagement"]},
            ]
            df = pd.DataFrame(comparison_data)
            fig = go.Figure(
                data=[
                    go.Bar(name="Avg Sales Lift %", x=df["Type"], y=df["Avg Lift %"], marker_color="#667eea"),
                    go.Bar(name="Avg Engagement", x=df["Type"], y=df["Avg Engagement"], marker_color="#764ba2"),
                ]
            )
            fig.update_layout(barmode="group", title="Reel vs Story Comparison")
            st.plotly_chart(fig, use_container_width=True)

        with col2:
            st.subheader("Revenue Timeline with Posts")
            timeline = get_revenue_with_posts_timeline(db, business_id(), 30)
            if timeline["revenue_data"]:
                df = pd.DataFrame(timeline["revenue_data"])
                df["date"] = pd.to_datetime(df["date"])
                fig = px.line(df, x="date", y="revenue", title="Daily Revenue (Last 30 Days)")
                fig.update_traces(line_color="#667eea")

                for marker in timeline["post_markers"]:
                    color = "#ff6b6b" if marker["type"] == "reel" else "#feca57"
                    marker_date = pd.to_datetime(marker["date"])
                    fig.add_shape(
                        type="line", x0=marker_date, x1=marker_date, y0=0, y1=1, yref="paper",
                        line=dict(color=color, width=1, dash="dash"),
                    )

                fig.update_layout(xaxis_title="Date", yaxis_title="Revenue (₹)", showlegend=False)
                st.plotly_chart(fig, use_container_width=True)
                st.caption("Dashed red = reel posted, dashed yellow = story posted")

        st.subheader("Individual Post Performance")
        posts_with_impact = get_posts_with_impact(db, business_id())
        if posts_with_impact:
            df = pd.DataFrame(posts_with_impact)
            fig = px.bar(
                df, x="posted_at", y="lift_percent", color="post_type",
                color_discrete_map={"reel": "#667eea", "story": "#feca57", "image": "#10b981"},
                title="Sales Lift % by Post", hover_data=["caption", "engagement", "incremental_revenue"],
            )
            fig.update_layout(xaxis_title="Post Date", yaxis_title="Sales Lift %")
            st.plotly_chart(fig, use_container_width=True)

            display_df = df[["posted_at", "post_type", "caption", "engagement", "lift_percent", "incremental_revenue"]].copy()
            display_df.columns = ["Date", "Type", "Caption", "Engagement", "Lift %", "Incremental ₹"]
            st.dataframe(display_df, use_container_width=True, hide_index=True)

            st.markdown("---")
            st.markdown("### Understanding the Metrics")
            st.markdown(
                """
            - **Sales Lift %**: How much daily revenue increased in the 3 days after posting compared to the 7-day baseline before
            - **Incremental Revenue**: Estimated additional revenue generated by each post
            - **Engagement**: Total likes, comments, and shares
            """
            )

    finally:
        db.close()
